
# -*- coding: utf-8 -*-
"""credoV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5ScqZmrojr1idI3W3nsGPMAIhzMB_s6
"""

import kagglehub

# Tải phiên bản mới nhất của bộ dữ liệu competition
# You need to authenticate with Kaggle to download the dataset.
# You can do this by uploading your kaggle.json file to your Colab environment
# or by setting KAGGLE_USERNAME and KAGGLE_KEY environment variables.
kagglehub.login()
path = kagglehub.competition_download('home-credit-default-risk')

print("Dữ liệu đã được tải về tại:", path)

# Cập nhật DATA_PATH để các cell sau sử dụng chính xác đường dẫn này
DATA_PATH = path

# Cell 1 — Import & Setup
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE

# Khai báo đường dẫn dữ liệu
DATA_PATH = '/root/.cache/kagglehub/competitions/home-credit-default-risk'

# Cell 2 — Load dữ liệu thô
app_train = pd.read_csv(os.path.join(DATA_PATH, 'application_train.csv'))
bureau = pd.read_csv(os.path.join(DATA_PATH, 'bureau.csv'))
prev = pd.read_csv(os.path.join(DATA_PATH, 'previous_application.csv'))
inst = pd.read_csv(os.path.join(DATA_PATH, 'installments_payments.csv'))

print(f"Application shape: {app_train.shape}")
print(f"Target distribution:\n{app_train['TARGET'].value_counts(normalize=True)}")

# Cell 3 — Stratified Split (Thực hiện trước mọi bước thống kê)
train_df, val_df = train_test_split(
    app_train,
    test_size=0.2,
    stratify=app_train['TARGET'],
    random_state=42
)

print(f"Train size: {train_df.shape[0]}, Val size: {val_df.shape[0]}")

# Cell 4 — Feature Engineering (Main Table)
def basic_fe_main(df):
    df = df.copy()
    # Xử lý anomaly
    df['DAYS_EMPLOYED'].replace(365243, np.nan, inplace=True)
    df['DAYS_BIRTH'] = abs(df['DAYS_BIRTH'])

    # Ratio features
    df['CREDIT_INCOME_PERCENT'] = df['AMT_CREDIT'] / df['AMT_INCOME_TOTAL']
    df['ANNUITY_INCOME_PERCENT'] = df['AMT_ANNUITY'] / df['AMT_INCOME_TOTAL']
    df['CREDIT_TERM'] = df['AMT_ANNUITY'] / df['AMT_CREDIT']
    df['DAYS_EMPLOYED_PERCENT'] = df['DAYS_EMPLOYED'] / df['DAYS_BIRTH']
    df['INCOME_PER_PERSON'] = df['AMT_INCOME_TOTAL'] / df['CNT_FAM_MEMBERS']
    return df

train_df = basic_fe_main(train_df)
val_df = basic_fe_main(val_df)

# Cell 5 — Aggregate bảng phụ (Chống Leakage)

def get_bureau_agg(bureau_df, target_ids):
    subset = bureau_df[bureau_df['SK_ID_CURR'].isin(target_ids)]
    agg = subset.groupby('SK_ID_CURR').agg({
        'DAYS_CREDIT': ['min', 'max', 'mean'],
        'AMT_CREDIT_SUM': ['max', 'mean', 'sum'],
        'AMT_CREDIT_SUM_DEBT': ['mean', 'sum'],
        'AMT_CREDIT_MAX_OVERDUE': ['max', 'mean'],
        'CNT_CREDIT_PROLONG': ['sum']
    })
    agg.columns = pd.Index(['BUREAU_' + e[0] + "_" + e[1].upper() for e in agg.columns.tolist()])
    return agg

def get_prev_app_agg(prev_df, target_ids):
    subset = prev_df[prev_df['SK_ID_CURR'].isin(target_ids)].copy()
    # Tính rate refused
    subset['IS_REFUSED'] = (subset['NAME_CONTRACT_STATUS'] == 'Refused').astype(int)
    agg = subset.groupby('SK_ID_CURR').agg({
        'AMT_APPLICATION': ['mean', 'max'],
        'AMT_CREDIT': ['mean'],
        'DAYS_DECISION': ['mean', 'min'],
        'IS_REFUSED': ['mean']
    })
    agg.columns = pd.Index(['PREV_' + e[0] + "_" + e[1].upper() for e in agg.columns.tolist()])
    agg.rename(columns={'PREV_IS_REFUSED_MEAN': 'PREV_REFUSED_RATE'}, inplace=True)
    return agg

def get_installments_agg(inst_df, target_ids):
    subset = inst_df[inst_df['SK_ID_CURR'].isin(target_ids)].copy()
    subset['PAYMENT_DIFF'] = subset['AMT_INSTALMENT'] - subset['AMT_PAYMENT']
    subset['DAYS_PAST_DUE'] = (subset['DAYS_INSTALMENT'] - subset['DAYS_ENTRY_PAYMENT']).clip(lower=0)
    subset['IS_LATE'] = (subset['DAYS_PAST_DUE'] > 0).astype(int)

    agg = subset.groupby('SK_ID_CURR').agg({
        'PAYMENT_DIFF': ['mean', 'sum'],
        'DAYS_PAST_DUE': ['mean', 'max'],
        'IS_LATE': ['sum']
    })
    agg.columns = pd.Index(['INST_' + e[0] + "_" + e[1].upper() for e in agg.columns.tolist()])
    agg.rename(columns={'INST_IS_LATE_SUM': 'INST_NUM_LATE'}, inplace=True)
    return agg

# Áp dụng riêng biệt cho train và val
for dataset, ids in [('train', train_df['SK_ID_CURR']), ('val', val_df['SK_ID_CURR'])]:
    b_agg = get_bureau_agg(bureau, ids)
    p_agg = get_prev_app_agg(prev, ids)
    i_agg = get_installments_agg(inst, ids)

    if dataset == 'train':
        train_df = train_df.join(b_agg, on='SK_ID_CURR', how='left').join(p_agg, on='SK_ID_CURR', how='left').join(i_agg, on='SK_ID_CURR', how='left')
    else:
        val_df = val_df.join(b_agg, on='SK_ID_CURR', how='left').join(p_agg, on='SK_ID_CURR', how='left').join(i_agg, on='SK_ID_CURR', how='left')

print(f"Join xong. Train shape: {train_df.shape}")

# Cell 6 — Encoding
cat_cols = train_df.select_dtypes('object').columns
le_map = {}

# 1. Label Encoding (<= 2 categories)
for col in cat_cols:
    if train_df[col].nunique() <= 2:
        le = LabelEncoder()
        train_df[col] = le.fit_transform(train_df[col].astype(str))
        # Map unknown categories in val to the first seen class
        val_df[col] = val_df[col].map(lambda s: s if s in le.classes_ else le.classes_[0])
        val_df[col] = le.transform(val_df[col].astype(str))
        le_map[col] = le

# 2. One-Hot Encoding
train_df = pd.get_dummies(train_df)
val_df = pd.get_dummies(val_df)

# 3. Align Columns
train_df, val_df = train_df.align(val_df, join='left', axis=1, fill_value=0)
print(f"Encoding xong. Total features: {train_df.shape[1]}")

# Cell 7 — Tách X, y
X_train = train_df.drop(columns=['TARGET', 'SK_ID_CURR'])
y_train = train_df['TARGET']
X_val = val_df.drop(columns=['TARGET', 'SK_ID_CURR'])
y_val = val_df['TARGET']

feature_cols = list(X_train.columns)

# Cell 8 — Imputation (Fit only on Train)
imputer = SimpleImputer(strategy='median')
X_train_imp = imputer.fit_transform(X_train)
X_val_imp = imputer.transform(X_val)

print("Imputation hoàn tất.")

# Cell 9A — Loại bỏ đặc trưng gần hằng số (VarianceThreshold)
# Chạy trên dữ liệu đã impute (numpy array), nên cần dùng feature_cols để tra tên

from sklearn.feature_selection import VarianceThreshold

vt = VarianceThreshold(threshold=0.01)   # phương sai < 0.01 → gần như hằng số
vt.fit(X_train_imp)                       # học từ train

X_train_vt = vt.transform(X_train_imp)
X_val_vt   = vt.transform(X_val_imp)

# Lưu lại danh sách cột được giữ
cols_after_vt = [col for col, keep in zip(feature_cols, vt.get_support()) if keep]
n_removed_vt  = len(feature_cols) - len(cols_after_vt)

print(f"VarianceThreshold: loại {n_removed_vt} cột → còn {len(cols_after_vt)} cột")

# Cell 9B — Chấm điểm thống kê độc lập với mô hình
# Fit HOÀN TOÀN trên X_train_vt để chống leakage

from sklearn.feature_selection import mutual_info_classif, chi2, SelectPercentile
import pandas as pd, numpy as np

# -- Thông tin tương hỗ: áp dụng cho TẤT CẢ cột số (kể cả OHE)
mi_scores = mutual_info_classif(X_train_vt, y_train, random_state=42)

# -- Chi²: chỉ áp dụng cho cột nhị phân/OHE (giá trị >= 0), clip âm nếu có
X_train_vt_pos = np.clip(X_train_vt, 0, None)   # chi2 yêu cầu không âm
chi2_scores, _ = chi2(X_train_vt_pos, y_train)

# -- Chuẩn hóa điểm về [0,1] để so sánh cùng thang
def normalize(arr):
    rng = arr.max() - arr.min()
    return (arr - arr.min()) / rng if rng > 0 else arr

mi_norm   = normalize(mi_scores)
chi2_norm = normalize(chi2_scores)

# Điểm tổng hợp thống kê = trung bình có trọng số
stat_score = 0.5 * mi_norm + 0.5 * chi2_norm

# Xếp hạng top features theo điểm thống kê
stat_df = pd.DataFrame({
    'feature'   : cols_after_vt,
    'mi_score'  : mi_scores,
    'chi2_score': chi2_scores,
    'stat_score': stat_score
}).sort_values('stat_score', ascending=False)

# Lấy top 60% cột theo điểm thống kê
TOP_STAT_PCT = 60
thresh_stat  = np.percentile(stat_score, 100 - TOP_STAT_PCT)
mask_stat    = stat_score >= thresh_stat

print(f"Thống kê: giữ top {TOP_STAT_PCT}% → {mask_stat.sum()} cột")
print(stat_df.head(15).to_string(index=False))

# Cell 9C — Feature importance từ mô hình cây tăng cường (LightGBM)
# Huấn luyện nhanh với n_estimators nhỏ, chỉ để chấm điểm đặc trưng

import lightgbm as lgb

lgb_selector = lgb.LGBMClassifier(
    n_estimators   = 300,
    learning_rate  = 0.05,
    num_leaves     = 63,
    subsample      = 0.8,
    colsample_bytree = 0.8,
    class_weight   = 'balanced',   # xử lý mất cân bằng khi chấm điểm
    random_state   = 42,
    n_jobs         = -1,
    verbose        = -1
)
lgb_selector.fit(X_train_vt, y_train.values)

lgb_importance = lgb_selector.feature_importances_          # gain-based
lgb_norm       = normalize(lgb_importance.astype(float))

# Top 60% theo LightGBM
thresh_lgb = np.percentile(lgb_norm, 100 - TOP_STAT_PCT)
mask_lgb   = lgb_norm >= thresh_lgb

lgb_df = pd.DataFrame({
    'feature'   : cols_after_vt,
    'lgb_importance': lgb_importance,
    'lgb_norm'  : lgb_norm
}).sort_values('lgb_importance', ascending=False)

print(f"LightGBM: giữ top {TOP_STAT_PCT}% → {mask_lgb.sum()} cột")
print(lgb_df.head(15).to_string(index=False))

# Cell 9D — Kết hợp 3 phương pháp bằng bỏ phiếu, áp mask cuối

import pandas as pd
import numpy as np

# ── Bước 1: Xếp hạng cột theo từng phương pháp ──────────────────────────────
n_cols = len(cols_after_vt)

# Rank từng phương pháp (rank cao = quan trọng hơn)
mi_rank   = pd.Series(mi_scores).rank(ascending=True).values      # MI score
chi2_rank = pd.Series(chi2_scores).rank(ascending=True).values    # Chi2 score
lgb_rank  = pd.Series(lgb_importance.astype(float)).rank(ascending=True).values  # LightGBM

# ── Bước 2: Điểm tổng hợp = trung bình rank của 3 phương pháp ───────────────
combined_rank = (mi_rank + chi2_rank + lgb_rank) / 3.0

# ── Bước 3: Chọn số features mục tiêu ────────────────────────────────────────
TARGET_FEATURES = min(130, n_cols)   # tối đa 130, hoặc ít hơn nếu không đủ

# Lấy index của top TARGET_FEATURES cột theo combined_rank
top_indices  = np.argsort(combined_rank)[-TARGET_FEATURES:]
top_indices  = np.sort(top_indices)   # giữ thứ tự cột

# ── Bước 4: Tạo mask và áp vào dữ liệu ──────────────────────────────────────
mask_final = np.zeros(n_cols, dtype=bool)
mask_final[top_indices] = True

selected_features = [cols_after_vt[i] for i in range(n_cols) if mask_final[i]]
dropped_features  = [cols_after_vt[i] for i in range(n_cols) if not mask_final[i]]

print(f"\n{'='*55}")
print(f"KẾT QUẢ CHỌN LỌC ĐẶC TRƯNG")
print(f"{'='*55}")
print(f"Trước VarianceThreshold : {len(feature_cols):>5} cột")
print(f"Sau  VarianceThreshold  : {n_cols:>5} cột")
print(f"Sau  rank tổng hợp      : {len(selected_features):>5} cột  ← dùng tiếp")
print(f"Tổng loại bỏ            : {len(feature_cols) - len(selected_features):>5} cột")

# Bảng top 15 features được chọn
summary_df = pd.DataFrame({
    'feature'      : cols_after_vt,
    'mi_score'     : mi_scores,
    'chi2_score'   : chi2_scores,
    'lgb_importance': lgb_importance,
    'combined_rank': combined_rank,
    'selected'     : mask_final
}).sort_values('combined_rank', ascending=False)

print("\nTop 15 features được chọn:")
print(summary_df[summary_df['selected']].head(15).to_string(index=False))

# ── Bước 5: Áp mask ──────────────────────────────────────────────────────────
X_train_sel = X_train_vt[:, mask_final]
X_val_sel   = vt.transform(X_val_imp)[:, mask_final]

# Cập nhật feature_cols cho các cell sau
feature_cols_sel = selected_features

print(f"\nX_train_sel : {X_train_sel.shape}")
print(f"X_val_sel   : {X_val_sel.shape}")

# Kiểm tra không có cột rỗng
assert X_train_sel.shape[1] > 0, "❌ Lỗi: X_train_sel rỗng!"
assert X_val_sel.shape[1]   > 0, "❌ Lỗi: X_val_sel rỗng!"
print("\n✅ Feature selection thành công — sẵn sàng sang Cell Scaling")

# Cell 10 — Scaling (cập nhật đầu vào)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_sel)   # ← đổi từ X_train_imp
X_val_scaled   = scaler.transform(X_val_sel)          # ← đổi từ X_val_imp

# Cell 11 — SMOTE Oversampling (target ratio = 0.3)
target_ratio = 0.3
sm_strategy = target_ratio / (1 - target_ratio)  # 0.3 / 0.7 ≈ 0.4286
sm = SMOTE(sampling_strategy=sm_strategy, random_state=42)
X_train_scaled, y_resampled = sm.fit_resample(X_train_scaled, y_train)
y_train = pd.Series(y_resampled, name='TARGET')
X_train_scaled = pd.DataFrame(X_train_scaled, columns=feature_cols_sel)
print(f"After SMOTE — Train: {X_train_scaled.shape}, Target rate: {y_train.mean():.4f}")

# Cell 12 — Kiểm tra & Summary
print("--- SUMMARY ---")
print(f"X_train shape (after SMOTE): {X_train_scaled.shape}")
print(f"X_val shape: {X_val_scaled.shape}")
print(f"Train Target Rate: {y_train.mean():.4f}")
print(f"Val Target Rate: {y_val.mean():.4f}")
print(f"Final Feature Count: {X_train_scaled.shape[1]}")
print(f"Số features: {X_train_scaled.shape[1]}")

# Cell 13 — Export
import pandas as pd

pd.DataFrame(X_train_scaled, columns=feature_cols_sel).to_csv('X_train_scaled.csv', index=False)
pd.DataFrame(X_val_scaled,   columns=feature_cols_sel).to_csv('X_val_scaled.csv',   index=False)
y_train.to_csv('y_train.csv', index=False)
y_val.to_csv('y_val.csv', index=False)

print("Đã lưu 4 file CSV có tên cột.")

"""### Tài liệu: Áp dụng dữ liệu vào mô hình Deep Learning

#### 1. Cấu trúc dữ liệu hiện tại
Sau khi chạy Pipeline, bạn có các tệp tin sau:
- `X_train_scaled.csv`: Ma trận đặc trưng (features) tập huấn luyện (246,008 mẫu × 267 đặc trưng).
- `X_val_scaled.csv`: Ma trận đặc trưng tập validation (61,503 mẫu × 267 đặc trưng).
- `y_train.csv` / `y_val.csv`: Nhãn mục tiêu (0: Bình thường, 1: Nợ xấu).

#### 2. Tại sao dữ liệu này phù hợp với Deep Learning?
- **Scaling**: Đã được xử lý bằng `StandardScaler`, giúp gradient descent hội tụ nhanh hơn.
- **Encoding**: Đã chuyển đổi tất cả categorical thành dạng số (Label/One-hot).
- **Imputation**: Các giá trị thiếu đã được xử lý bằng Median (fit từ tập Train).

#### 3. Cách sử dụng `class_weight_dict`
Vì dữ liệu mất cân bằng (~8% positive), khi huấn luyện mô hình Deep Learning, bạn nên:
- Sử dụng `WeightedRandomSampler` trong PyTorch.
- Hoặc truyền trọng số vào Loss Function (ví dụ: `pos_weight` trong `BCEWithLogitsLoss` của PyTorch hoặc `class_weight` trong Keras).

#### 4. Code mẫu nạp dữ liệu nhanh
"""

import torch
from torch.utils.data import TensorDataset, DataLoader

# Chuyển đổi từ numpy/csv sang torch Tensor
def create_dataloader(X_path, y_path, batch_size=1024, shuffle=True):
    X = pd.read_csv(X_path).values
    y = pd.read_csv(y_path).values.flatten()

    tensor_x = torch.Tensor(X)
    tensor_y = torch.Tensor(y)

    dataset = TensorDataset(tensor_x, tensor_y)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

# Ví dụ nạp dữ liệu
# train_loader = create_dataloader('X_train_scaled.csv', 'y_train.csv')
# val_loader = create_dataloader('X_val_scaled.csv', 'y_val.csv', shuffle=False)

print("Sẵn sàng nạp vào mô hình Deep Learning.")

"""### Chi tiết về các bảng trong bộ dữ liệu

Bộ dữ liệu này có cấu trúc phân cấp (relational), xoay quanh bảng hồ sơ vay chính. Dưới đây là mô tả chi tiết:

1.  **application_{train|test}.csv (Bảng chính):**
    *   Mỗi hàng là một khoản vay tại Home Credit.
    *   Chứa thông tin cá nhân của khách hàng: Thu nhập, học vấn, tình trạng hôn nhân, nghề nghiệp, và các chỉ số tài chính tại thời điểm nộp đơn.
    *   **TARGET**: 1 là có hành vi thanh toán trễ (rủi ro), 0 là thanh toán đúng hạn.

2.  **bureau.csv:**
    *   Chứa thông tin tất cả các khoản vay trước đó của khách hàng tại **các tổ chức tài chính khác** (ngân hàng khác) mà Credit Bureau (Trung tâm thông tin tín dụng) ghi nhận được.
    *   Mỗi khách hàng trong bảng chính có thể có nhiều hàng trong bảng này tương ứng với nhiều khoản vay cũ.

3.  **previous_application.csv:**
    *   Lịch sử tất cả các đơn xin vay **trước đây của chính khách hàng đó tại Home Credit**.
    *   Bảng này cho biết khách hàng đã từng bị từ chối hay được phê duyệt trong quá khứ.

4.  **Các bảng theo dõi hành vi thanh toán (Dữ liệu chuỗi thời gian):**
    *   **bureau_balance.csv**: Số dư hàng tháng của các khoản vay trong bảng `bureau`.
    *   **POS_CASH_balance.csv**: Số dư hàng tháng của các khoản vay tín chấp hoặc vay mua hàng trả góp cũ.
    *   **credit_card_balance.csv**: Số dư hàng tháng của thẻ tín dụng mà khách hàng đã có với Home Credit.
    *   **installments_payments.csv**: Lịch sử thanh toán thực tế (số tiền đã trả và ngày trả thực tế so với ngày dự kiến).

**Sơ đồ liên kết:**
*   `application_train` kết nối với tất cả các bảng qua `SK_ID_CURR`.
*   `bureau` kết nối với `bureau_balance` qua `SK_ID_BUREAU`.
*   `previous_application` kết nối với các bảng POS, Installments, Credit Card qua `SK_ID_PREV`.

## Báo cáo Quy trình Dữ liệu & Tiền xử lý

### 1. Nguồn dữ liệu & Cấu trúc (Data Source)
Bộ dữ liệu được sử dụng từ cuộc thi **Home Credit Default Risk** trên Kaggle. Đây là dạng dữ liệu bảng liên kết (Relational Data) bao gồm:
- **Bảng chính (Application)**: Chứa thông tin tĩnh của khách hàng tại thời điểm nộp đơn.
- **Bảng phụ (Bureau, Previous Apps, Installments)**: Ghi lại lịch sử tín dụng quá khứ, hành vi thanh toán và các khoản vay cũ.
- **Mục tiêu (Target)**: Dự đoán xác suất khách hàng gặp khó khăn trong việc thanh toán (Target=1).

### 2. Quy trình Tiền xử lý & Kiểm soát Rò rỉ (Pipeline & Leakage Control)
Để đảm bảo tính khách quan và khả năng tổng quát hóa của mô hình, quy trình tuân thủ nghiêm ngặt các bước:
- **Stratified Splitting**: Chia dữ liệu theo tỷ lệ 80/20 dựa trên biến mục tiêu trước khi thực hiện bất kỳ phép tính thống kê nào.
- **Independent Aggregation**: Việc tổng hợp dữ liệu từ các bảng phụ (Bureau, Installments,...) được thực hiện độc lập cho tập Train và tập Validation dựa trên ID. Điều này triệt tiêu hoàn toàn lỗi 'nhìn trước tương lai' (look-ahead bias).
- **Feature Engineering**: Tập trung vào các chỉ số tài chính (Financial Ratios) như `CREDIT_INCOME_PERCENT`, `ANNUITY_INCOME_PERCENT`, và `DAYS_EMPLOYED_PERCENT` để nắm bắt khả năng trả nợ của khách hàng.

### 3. Khả năng Làm sạch & Chuẩn hóa (Cleaning & Standardization)
Hệ thống tự động hóa các thao tác xử lý dữ liệu thô:
- **Xử lý Anomaly**: Tự động phát hiện và thay thế các giá trị bất thường (ví dụ: `DAYS_EMPLOYED` = 365243 ngày) bằng giá trị trống.
- **Smart Imputation**: Sử dụng `SimpleImputer` với chiến lược `median`. Giá trị trung vị được tính toán **chỉ từ tập Train** và áp dụng ngược lại cho tập Validation.
- **Categorical Encoding**: Kết hợp `Label Encoding` cho các biến nhị phân và `One-Hot Encoding` cho các biến đa danh mục, kèm theo bước căn chỉnh cột (Aligning) để đảm bảo cấu trúc input đồng nhất.
- **Standardization**: Sử dụng `StandardScaler` để đưa các đặc trưng về phân phối chuẩn (Mean=0, Std=1), giúp các mô hình mạng thần kinh (Deep Learning) và Gradient Boosting hội tụ hiệu quả hơn.

# BÁO CÁO CHI TIẾT QUY TRÌNH XỬ LÝ DỮ LIỆU

### 1. Nguồn dữ liệu (Data Source & Relational Structure)

Dữ liệu được trích xuất từ cuộc thi **Home Credit Default Risk** trên Kaggle. Đây là một hệ thống dữ liệu quan hệ phức tạp, phản ánh chân thực các thông tin ngân hàng:

*   **Dữ liệu tĩnh (Static Data):** Chứa trong bảng `application`, bao gồm các thuộc tính định danh khách hàng, thông tin nhân khẩu học và tài chính tại thời điểm đăng ký vay.
*   **Lịch sử tín dụng ngoài (External History):** Bảng `bureau` ghi lại các khoản vay của khách hàng tại các tổ chức tài chính khác.
*   **Lịch sử nội bộ (Internal History):** Bảng `previous_application` lưu trữ các đơn vay cũ, bao gồm cả những đơn bị từ chối.
*   **Hành vi thanh toán (Behavioral Data):** Các bảng `installments_payments` cung cấp chi tiết từng lần trả nợ, giúp nhận diện thói quen thanh toán trễ.

---

### 2. Quy trình Tiền xử lý (Preprocessing Pipeline)

Quy trình được thiết kế theo tiêu chuẩn công nghiệp nhằm đảm bảo mô hình có độ tin cậy cao nhất:

#### Kiểm soát rò rỉ dữ liệu (Leakage Control)
*   **Chiến thuật "Split-First":** Dữ liệu được chia tập **Train/Validation** ngay từ đầu. Mọi tính toán thống kê (Mean, Median, Std) chỉ được thực hiện trên tập Train.
*   **ID-Based Aggregation:** Việc tổng hợp (Aggregate) dữ liệu từ bảng phụ được lọc theo danh sách ID của từng tập, đảm bảo thông tin từ tập Validation không bao giờ lọt vào quá trình huấn luyện.

#### Kỹ thuật đặc trưng (Feature Engineering)
*   **Chỉ số tài chính:** Tạo ra các biến tỷ lệ (Ratios) như Tín dụng/Thu nhập, Trả góp/Thu nhập để đo lường áp lực tài chính.
*   **Dấu ấn thời gian:** Chuyển đổi các cột ngày tháng thành số tương đối và xử lý các giá trị vô lý (ví dụ: số ngày làm việc hơn 100 năm).

#### Mã hóa & Căn chỉnh (Encoding & Alignment)
*   **Label Encoding:** Áp dụng cho các biến nhị phân (Nam/Nữ, Có/Không).
*   **One-Hot Encoding:** Chuyển đổi các biến danh mục đa lớp thành ma trận thưa.
*   **Feature Alignment:** Đảm bảo cả hai tập dữ liệu có cùng số lượng và thứ tự các cột đặc trưng sau khi mã hóa.

---

### 3. Khả năng làm sạch & Chuẩn hóa (Cleaning & Scaling)

*   **Xử lý dữ liệu thiếu (Imputation):** Sử dụng `Median` để điền vào các ô trống. Phương pháp này bền vững hơn `Mean` đối với các dữ liệu có nhiều giá trị ngoại lai (outliers).
*   **Chuẩn hóa Deep Learning (Standardization):**
    *   Sử dụng `StandardScaler` để đưa dữ liệu về phân phối có trung bình bằng 0 và độ lệch chuẩn bằng 1.
    *   **Lợi ích:** Giúp các hàm kích hoạt (Activation Functions) và thuật toán Gradient Descent hoạt động ổn định và hội tụ nhanh hơn gấp nhiều lần.

---

### 4. Khả năng phân tích (EDA & Monitoring)

*   **Kiểm tra mất cân bằng:** Hệ thống theo dõi tỷ lệ `Target` (hiện tại là ~8% nợ xấu) để tự động tính toán trọng số lớp (`Class Weights`).
*   **Thống kê hình khối:** Kiểm tra hình dạng (Shape) và kiểu dữ liệu sau mỗi bước biến đổi để đảm bảo tính toàn vẹn của dữ liệu.
*   **Sẵn sàng mô hình:** Kết quả đầu ra là các tệp CSV đã chuẩn hóa, có thể nạp trực tiếp vào các framework như **PyTorch**, **TensorFlow** hoặc **XGBoost** mà không cần xử lý thêm.
"""

