// <auto-generated />
using System;
using CreditScoringAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditScoringAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530190518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "contract_status", new[] { "Approved", "Refused", "Canceled", "Unused offer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "contract_type", new[] { "Cash loans", "Revolving loans" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "education_type", new[] { "Secondary / secondary special", "Higher education", "Incomplete higher", "Lower secondary", "Academic degree" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "emergency_state", new[] { "No", "Yes" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "family_status", new[] { "Single / not married", "Married", "Civil marriage", "Widow", "Separated" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fondkapremont", new[] { "reg oper account", "org spec account", "reg oper spec account", "not specified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gender_type", new[] { "M", "F" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "housetype_mode", new[] { "block of flats", "terraced house", "specific housing" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "housing_type", new[] { "House / apartment", "Rented apartment", "With parents", "Municipal apartment", "Office apartment", "Co-op apartment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "income_type", new[] { "Working", "State servant", "Commercial associate", "Pensioner", "Unemployed", "Student", "Businessman", "Maternity leave" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "occupation_type", new[] { "Laborers", "Core staff", "Accountants", "Managers", "Drivers", "Sales staff", "Cleaning staff", "Cooking staff", "Private service staff", "Medicine staff", "Security staff", "High skill tech staff", "Waiters/barmen staff", "Low-skill Laborers", "Realty agents", "Secretaries", "IT staff", "HR staff" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "organization_type", new[] { "Business Entity Type 1", "Business Entity Type 2", "Business Entity Type 3", "School", "Government", "Religion", "Other", "XNA", "Electricity", "Medicine", "Self-employed", "Transport: type 1", "Transport: type 2", "Transport: type 3", "Transport: type 4", "Construction", "Housing", "Kindergarten", "Trade: type 1", "Trade: type 2", "Trade: type 3", "Trade: type 4", "Trade: type 5", "Trade: type 6", "Trade: type 7", "Industry: type 1", "Industry: type 2", "Industry: type 3", "Industry: type 4", "Industry: type 5", "Industry: type 6", "Industry: type 7", "Industry: type 8", "Industry: type 9", "Industry: type 10", "Industry: type 11", "Industry: type 12", "Industry: type 13", "Military", "Services", "Security Ministries", "Police", "Postal", "Agriculture", "Restaurant", "Culture", "Hotel", "Bank", "Insurance", "Mobile", "Legal Services", "Advertising", "Cleaning", "Telecom", "Realtor", "University", "Emergency", "Security" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "prediction_result", new[] { "DEFAULT", "NON_DEFAULT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "suite_type", new[] { "Unaccompanied", "Family", "Spouse", " partner", "Children", "Other_A", "Other_B", "Group of people" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wallsmaterial", new[] { "Stone", " brick", "Block", "Panel", "Mixed", "Wooden", "Others", "Monolith" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.CreditBureauHistory", b =>
                {
                    b.Property<int>("BureauId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bureau_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("BureauId"));

                    b.Property<decimal?>("AmtAnnuity")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amt_annuity");

                    b.Property<decimal>("AmtCreditMaxOverdue")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_credit_max_overdue");

                    b.Property<decimal>("AmtCreditSum")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_credit_sum");

                    b.Property<decimal>("AmtCreditSumDebt")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_credit_sum_debt");

                    b.Property<decimal?>("AmtCreditSumLimit")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_credit_sum_limit");

                    b.Property<decimal>("AmtCreditSumOverdue")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_credit_sum_overdue");

                    b.Property<short>("CntCreditProlong")
                        .HasColumnType("smallint")
                        .HasColumnName("cnt_credit_prolong");

                    b.Property<string>("CreditActive")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credit_active");

                    b.Property<int>("CreditDayOverdue")
                        .HasColumnType("integer")
                        .HasColumnName("credit_day_overdue");

                    b.Property<string>("CreditType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("credit_type");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("DaysCredit")
                        .HasColumnType("integer")
                        .HasColumnName("days_credit");

                    b.Property<int?>("DaysCreditEnddate")
                        .HasColumnType("integer")
                        .HasColumnName("days_credit_enddate");

                    b.Property<int?>("DaysEnddateFact")
                        .HasColumnType("integer")
                        .HasColumnName("days_enddate_fact");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.HasKey("BureauId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_bureau_customer");

                    b.ToTable("credit_bureau_history", (string)null);
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CustomerId"));

                    b.Property<decimal>("AmtIncomeTotal")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_income_total");

                    b.Property<short>("AmtReqCreditBureauDay")
                        .HasColumnType("smallint")
                        .HasColumnName("amt_req_credit_bureau_day");

                    b.Property<short>("AmtReqCreditBureauMon")
                        .HasColumnType("smallint")
                        .HasColumnName("amt_req_credit_bureau_mon");

                    b.Property<short>("AmtReqCreditBureauQrt")
                        .HasColumnType("smallint")
                        .HasColumnName("amt_req_credit_bureau_qrt");

                    b.Property<short>("AmtReqCreditBureauYear")
                        .HasColumnType("smallint")
                        .HasColumnName("amt_req_credit_bureau_year");

                    b.Property<short>("CntChildren")
                        .HasColumnType("smallint")
                        .HasColumnName("cnt_children");

                    b.Property<short>("CntFamMembers")
                        .HasColumnType("smallint")
                        .HasColumnName("cnt_fam_members");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<short>("Def30CntSocialCircle")
                        .HasColumnType("smallint")
                        .HasColumnName("def_30_cnt_social_circle");

                    b.Property<short>("Def60CntSocialCircle")
                        .HasColumnType("smallint")
                        .HasColumnName("def_60_cnt_social_circle");

                    b.Property<int?>("EducationType")
                        .HasColumnType("education_type")
                        .HasColumnName("education_type");

                    b.Property<decimal?>("ElevatorsAvg")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("elevators_avg");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int?>("EmergencyState")
                        .HasColumnType("emergency_state")
                        .HasColumnName("emergencystate_mode");

                    b.Property<DateOnly?>("EmploymentSince")
                        .HasColumnType("date")
                        .HasColumnName("employment_since");

                    b.Property<decimal?>("ExtSource1")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("ext_source_1");

                    b.Property<decimal?>("ExtSource2")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("ext_source_2");

                    b.Property<decimal?>("ExtSource3")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("ext_source_3");

                    b.Property<int?>("FamilyStatus")
                        .HasColumnType("family_status")
                        .HasColumnName("family_status");

                    b.Property<bool>("FlagDocument3")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_document_3");

                    b.Property<bool>("FlagDocument6")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_document_6");

                    b.Property<bool>("FlagDocument8")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_document_8");

                    b.Property<bool>("FlagEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_email");

                    b.Property<bool>("FlagEmpPhone")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_emp_phone");

                    b.Property<bool>("FlagOwnCar")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_own_car");

                    b.Property<bool>("FlagOwnRealty")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_own_realty");

                    b.Property<bool>("FlagPhone")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_phone");

                    b.Property<bool>("FlagWorkPhone")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_work_phone");

                    b.Property<decimal?>("FloorsMaxAvg")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("floorsmax_avg");

                    b.Property<decimal?>("FloorsMaxMedi")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("floorsmax_medi");

                    b.Property<decimal?>("FloorsMaxMode")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("floorsmax_mode");

                    b.Property<int?>("Fondkapremont")
                        .HasColumnType("fondkapremont")
                        .HasColumnName("fondkapremont_mode");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("gender_type")
                        .HasColumnName("gender");

                    b.Property<int?>("HousetypeMode")
                        .HasColumnType("housetype_mode")
                        .HasColumnName("housetype_mode");

                    b.Property<int?>("HousingType")
                        .HasColumnType("housing_type")
                        .HasColumnName("housing_type");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_number");

                    b.Property<DateOnly?>("IdPublishDate")
                        .HasColumnType("date")
                        .HasColumnName("id_publish_date");

                    b.Property<int?>("IncomeType")
                        .HasColumnType("income_type")
                        .HasColumnName("income_type");

                    b.Property<DateOnly?>("LastPhoneChangeDate")
                        .HasColumnType("date")
                        .HasColumnName("last_phone_change_date");

                    b.Property<bool>("LiveCityNotWorkCity")
                        .HasColumnType("boolean")
                        .HasColumnName("live_city_not_work_city");

                    b.Property<bool>("LiveRegionNotWorkRegion")
                        .HasColumnType("boolean")
                        .HasColumnName("live_region_not_work_region");

                    b.Property<short>("Obs30CntSocialCircle")
                        .HasColumnType("smallint")
                        .HasColumnName("obs_30_cnt_social_circle");

                    b.Property<short>("Obs60CntSocialCircle")
                        .HasColumnType("smallint")
                        .HasColumnName("obs_60_cnt_social_circle");

                    b.Property<int?>("OccupationType")
                        .HasColumnType("occupation_type")
                        .HasColumnName("occupation_type");

                    b.Property<int?>("OrganizationType")
                        .HasColumnType("organization_type")
                        .HasColumnName("organization_type");

                    b.Property<short?>("OwnCarAge")
                        .HasColumnType("smallint")
                        .HasColumnName("own_car_age");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("RegCityNotLiveCity")
                        .HasColumnType("boolean")
                        .HasColumnName("reg_city_not_live_city");

                    b.Property<bool>("RegCityNotWorkCity")
                        .HasColumnType("boolean")
                        .HasColumnName("reg_city_not_work_city");

                    b.Property<bool>("RegRegionNotWorkRegion")
                        .HasColumnType("boolean")
                        .HasColumnName("reg_region_not_work_region");

                    b.Property<short?>("RegionRatingClient")
                        .HasColumnType("smallint")
                        .HasColumnName("region_rating_client");

                    b.Property<short?>("RegionRatingClientWCity")
                        .HasColumnType("smallint")
                        .HasColumnName("region_rating_client_w_city");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("registration_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WallsmaterialMode")
                        .HasColumnType("wallsmaterial")
                        .HasColumnName("wallsmaterial_mode");

                    b.HasKey("CustomerId");

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("customers", null, t =>
                        {
                            t.HasCheckConstraint("CK_customers_amt_income_total", "amt_income_total > 0");

                            t.HasCheckConstraint("CK_customers_cnt_children", "cnt_children >= 0");

                            t.HasCheckConstraint("CK_customers_cnt_fam_members", "cnt_fam_members >= 1");

                            t.HasCheckConstraint("CK_customers_region_rating", "region_rating_client BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_customers_region_rating_city", "region_rating_client_w_city BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.InstallmentPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmtInstalment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amt_instalment");

                    b.Property<decimal?>("AmtPayment")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amt_payment");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DaysEntryPayment")
                        .HasColumnType("integer")
                        .HasColumnName("days_entry_payment");

                    b.Property<int>("DaysInstalment")
                        .HasColumnType("integer")
                        .HasColumnName("days_instalment");

                    b.Property<short?>("NumInstalmentNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("num_instalment_number");

                    b.Property<short?>("NumInstalmentVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("num_instalment_version");

                    b.Property<int?>("PrevAppId")
                        .HasColumnType("integer")
                        .HasColumnName("prev_app_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("PaymentId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_inst_customer");

                    b.HasIndex("PrevAppId");

                    b.ToTable("installment_payments", (string)null);
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.LoanApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ApplicationId"));

                    b.Property<decimal>("AmtAnnuity")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amt_annuity");

                    b.Property<decimal>("AmtCredit")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_credit");

                    b.Property<decimal?>("AmtGoodsPrice")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_goods_price");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("NameContractType")
                        .HasColumnType("contract_type")
                        .HasColumnName("name_contract_type");

                    b.Property<int?>("NameTypeSuite")
                        .HasColumnType("suite_type")
                        .HasColumnName("name_type_suite");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CustomerId");

                    b.ToTable("loan_applications", null, t =>
                        {
                            t.HasCheckConstraint("CK_loan_amt_annuity", "amt_annuity > 0");

                            t.HasCheckConstraint("CK_loan_amt_credit", "amt_credit > 0");

                            t.HasCheckConstraint("CK_loan_status", "status IN ('pending','approved','rejected')");
                        });
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.ModelPrediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prediction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("PredictionId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("FeatureVector")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_vector");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_type");

                    b.Property<DateTime>("PredictedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("predicted_at");

                    b.Property<decimal>("ProbabilityDefault")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("probability_default");

                    b.Property<int>("Result")
                        .HasColumnType("prediction_result")
                        .HasColumnName("result");

                    b.Property<decimal>("ThresholdUsed")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("threshold_used");

                    b.HasKey("PredictionId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("idx_pred_application");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_pred_customer");

                    b.ToTable("model_predictions", null, t =>
                        {
                            t.HasCheckConstraint("CK_pred_model_type", "model_type IN ('ANN', 'LSTM')");

                            t.HasCheckConstraint("CK_pred_probability", "probability_default BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.PreviousLoanApplication", b =>
                {
                    b.Property<int>("PrevAppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prev_app_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("PrevAppId"));

                    b.Property<decimal>("AmtApplication")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_application");

                    b.Property<decimal?>("AmtCredit")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amt_credit");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("DaysDecision")
                        .HasColumnType("integer")
                        .HasColumnName("days_decision");

                    b.Property<int>("NameContractStatus")
                        .HasColumnType("contract_status")
                        .HasColumnName("name_contract_status");

                    b.HasKey("PrevAppId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_prev_app_customer");

                    b.ToTable("previous_loan_applications", (string)null);
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.CreditBureauHistory", b =>
                {
                    b.HasOne("CreditScoringAPI.Models.Entities.Customer", "Customer")
                        .WithMany("CreditBureauHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.InstallmentPayment", b =>
                {
                    b.HasOne("CreditScoringAPI.Models.Entities.Customer", "Customer")
                        .WithMany("InstallmentPayments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreditScoringAPI.Models.Entities.PreviousLoanApplication", "PreviousLoanApplication")
                        .WithMany("InstallmentPayments")
                        .HasForeignKey("PrevAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("PreviousLoanApplication");
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.LoanApplication", b =>
                {
                    b.HasOne("CreditScoringAPI.Models.Entities.Customer", "Customer")
                        .WithMany("LoanApplications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.ModelPrediction", b =>
                {
                    b.HasOne("CreditScoringAPI.Models.Entities.LoanApplication", "LoanApplication")
                        .WithMany("ModelPredictions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreditScoringAPI.Models.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.PreviousLoanApplication", b =>
                {
                    b.HasOne("CreditScoringAPI.Models.Entities.Customer", "Customer")
                        .WithMany("PreviousLoanApplications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.Customer", b =>
                {
                    b.Navigation("CreditBureauHistories");

                    b.Navigation("InstallmentPayments");

                    b.Navigation("LoanApplications");

                    b.Navigation("PreviousLoanApplications");
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.LoanApplication", b =>
                {
                    b.Navigation("ModelPredictions");
                });

            modelBuilder.Entity("CreditScoringAPI.Models.Entities.PreviousLoanApplication", b =>
                {
                    b.Navigation("InstallmentPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
